// Every string the app shows. One enum, so the copy gate and the tests read
// one list. Voice: plain, present tense, second person, no exclamation
// marks. Nothing here claims proof — ADR-0003 — and `make copy-check` reads
// this file for the words that would.
enum Strings {
    static let appName = "Snag"
    static let reports = "Reports"
    static let emptyTitle = "Start with the flat you're standing in."
    static let emptyHint = "Walk it room by room. Photograph what's wrong. Seal it before the boxes are in."
    static let newReport = "New report"
    static let address = "Address"
    static let addressPlaceholder = "14 Admiralty Way, Lekki"
    static let kind = "Kind"
    static let moveIn = "Move-in"
    static let moveOut = "Move-out"
    static let startWalk = "Walk the flat"
    static let addRoom = "Add a room"
    static let room = "Room"
    static let roomNamePlaceholder = "What is this room called?"
    static let nextRoom = "Next room"
    static let takePhoto = "Photograph"
    static let caption = "What's wrong, in a sentence"
    static let snag = "Snag"
    static let fine = "Fine"
    static let review = "Review"
    static let seal = "Seal"
    static let sealed = "Sealed"
    static let unaltered = "Unaltered since signing"
    static let altered = "Altered"
    static let alteredHint = "This bundle has been changed since it was sealed. The report shown below may not be what was signed."
    static let datedByPhone = "dated by the phone that made it"
    static let items = "items"
    static let snags = "snags"
    static let done = "Done"
    static let cancel = "Cancel"
    static let tierPhotographed = "photographed"
    static let tierMeasured = "measured"
    static let tierScanned = "scanned"
    static let skip = "Skip"
    static let measureRoom = "Measure this room"
    static let measureHint = "Tap each corner of the floor."
}
